### ISSUE TITLE
Admin Create new events

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#21]
## Current Portal
<img width="1508" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/9f3f8c8f-efa6-4bf9-9c7a-4e9920f711a5">

## Design
<img width="805" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/f766543d-e852-4707-814e-3c103cbd48dc">
<img width="804" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/98247f7c-45c3-4693-a184-20843ba4af0f">
<img width="805" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/684e8a2d-af97-4e08-8599-1f5026cb8fce">

## Tasks
- [ ] Fix the overlapping text issue
<img width="893" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/609989c9-d337-4fe7-89c3-fb3b7c4ecb56">

- [ ] Implement the `Create` functionality
- [ ] If you have time, implement the design
