### ISSUE TITLE
Filter events by tags in admin portal

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#22]
## Tasks
- [x]  Change bookem-shared database model so that tags contains an array of events
- [x]  Add a column called program in event table between volunteer and tags
- [ ]  Select events by tags + select events by program (no specific design on figma so use your imagination and ant design examples). 
    - [x] Add an end point that returns all programs
    - [x] Add an end point that returns all tags
    - [ ] Filter events by tags
    - [ ] Filter events by programs
