### ISSUE TITLE
Tag Management Frontend

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#23]
## Current:
<img width="1512" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/bd0dedc4-7b30-4a3d-8c5c-550ce2faefc0">

## Design:
<img width="779" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/e62ad871-03f1-4c39-ac8f-ffa3fdba7864">

## Tasks:
- [x] Implement the frontend design. You might need to use the `<PopupWindow/>` component. Jessie worked on it before so consult her on how to use it. 
- [x] Implement the info button that displays instructions on hover and focus
- [ ] If you have time, work on the functionality by connecting with backend.
