### ISSUE TITLE
Connect backend to the program table

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#25]
## Current:
<img width="1512" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/f84ba9f3-789c-42a2-bbbe-ebc5327da83f">

## Tasks
- [x] Take over @huongthaoh's PR. 
- [x] Remove Search
- [x] Link database data to the frontend
- [x] Add a new column, each row with a button called `see events`
- [x] Add a new column, each row with a button called `see volunteers`
- [ ] If you have time, display all the events for a specific program. There's currently no design for it so it can be barebone HTML.
