### ISSUE TITLE
Admin Setting Page Table

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#26]
## Design: 
<img width="902" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/b1ba4e55-265e-4a9d-b900-49c00bc9a8c5">

## Tasks
- [x] Implement the frontend with fake data
- [x] Implement a backend API endpoint that returns all admin information
- [x] Display the data retrieved from the backend.
