### ISSUE TITLE
See all events in a program

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#33]
<img width="1512" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/fecd320b-a8e3-4167-ace8-e1dfdae86457">

## Tasks
- [x] First clean up some stuff
  - [x] Add a profile picture to the top left corner (same as Bookem-user)
  - [x] Add a label under each sidebar icon (same as Bookem-user)
  - [x] Fix the margin issue in this page
  - [x] Change the icon of the Program sidebar icon (refer to figma design). 
  - [x] Add a sorter for the "Number of Events" column
- [ ] After clicking "See Events", it should display a page with an event table
  - [x] Implement a backend API endpoint that returns all events given a program ID: `/api/events/program/[id]`
  - [x] Add a new page `pages/events/program/[id]` that displays all events in a program 
  - [ ] A smart way to approach this is to add a new component in `components/table/event-table` that "inherits" from EventTable. We can do this together since you need to make some changes to the current architecture. 
<img width="829" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/52fbb4d2-c39a-4615-8ae0-89a89ad79831">
