### ISSUE TITLE
CRUD Operations for tags

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#35]
# Tasks
<img width="1000" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/dc896fce-b193-4167-9273-252090b2b43f">

- [x] Implement the backend API endpoints for tags
  - [x] GET `/api/tags`: Return all tags in database
  - [x] POST: `/api/tags`: Create a new tag. The `events` array should be empty. 
  - [x] PUT: `/api/tags/[id]`: Edit tag's name. 
  - [x] DELETE: `/api/tags/[id]`: Delete a tag. Should also go through all `events` since each event contains a `tags` array. 
- [ ] Implement frontend
  - [x] Turn tags data on frontend into real data from the database
  - [x] Implement adding a new tag
  - [ ] Implement editing tag's name
  - [ ] Implement deleting a tag. Should have a confirm popup. Can use `antd` for this.
