### ISSUE TITLE
Volunteer Log Backend

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#36]
# Tasks
- [ ] Make all emails clickable. 
- [ ] Implement API endpoints for volunteer logs. 
  - [ ] GET `/api/volunteerLogs`: Return all volunteer logs. The current endpoint is wrong and unused. 
  - [ ] POST `/api/volunteerLogs`: Create a new volunteer log. Refer to the one in Bookem-user.
