### ISSUE TITLE
User Setting Page

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#45]
## Tasks
Follow the HiFi design on Figma and implement the frontend design for user setting page. Email notifications can wait until later when we get our domain name. 
- [ ] Implement the small sidebar and log out button
- [ ] Implement the Edit Profile form (filled with fake data)
- [ ] Implement the Change Password form
<img width="641" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/7abd3e0f-8571-45f7-8ae8-de8a677fc133">
<img width="639" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/f5fa5377-d7db-4f75-a53c-e99e080c62a8">
