### ISSUE TITLE
Main page design

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#50]
## Tasks
- [ ] Create a backend API endpoint `/api/events/featured` that gets all events with tag `featured`. 
- [ ] Implement frontend design with fake data
- [ ] Replace fake data with real data fetched from backend
<img width="1086" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/c0ca7711-24bf-4e34-8dfa-491f6fc9fa9a">
