### ISSUE TITLE
Volunteer Detail Page Design

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-admin#53]
## Tasks
- [ ] Implement the Volunteer General Info page design
- [ ] Integrate with backend data
- [ ] If you have time, implement the Background Check design
<img width="706" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-admin/assets/98133282/a6e194cc-6dc1-463a-9f77-ef306a3935fa">
